version: "{build}"
image: Visual Studio 2017
environment:
  TRAVIS_REPO_SLUG: olive-editor/olive

# Hack to not buid the "continuous" tag (https://github.com/appveyor/ci/issues/486)
# FIXME: Will unforttunately skip release tags
skip_tags: true

install:
  - cd C:\Tools\vcpkg
  - git pull
  - .\bootstrap-vcpkg.bat
  - cd %APPVEYOR_BUILD_FOLDER%
build_script:
  - cmd: appveyor-build.bat
artifacts:
  - path: Olive*.zip
    name: Olive Portable
  - path: Olive*.exe
    name: Olive Installer
cache: c:\tools\vcpkg\installed\
